image: rust:latest

stages:
  #- build
  - test_unit

#build:
#  stage: build
#  script:
#    - apt-get update
#    - apt-get install -y clang
#    - cd ..
#    - rm -rf vade
#    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade.git --branch develop
#    - cd vade-didcomm
#    - cargo build --release --verbose

test_unit:
  stage: test_unit
  script:
    - apt-get update
    - apt-get install -y clang
    - cd ..
    - rm -rf vade
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade.git --branch develop
    - rustup component add clippy
    - cd vade-didcomm
    - ls -la .git
    - RUST_BACKTRACE=1 RUST_LOG=trace cargo test --verbose
