image: rust:latest

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/".insteadOf 'https://git.slock.it/'

stages:
  - build
  - test_unit

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y clang
    - cd ..
    - rm -rf vade
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade.git --branch develop
    - cd vade-didcomm
    - cargo build --release --verbose

test_unit:
  stage: test_unit
  script:
    - apt-get update
    - apt-get install -y clang
    - mkdir -p .git/hooks
    - cargo test --release
